name: tflow
channels:
  - defaults
dependencies:
  - scikit-learn=0.23.2
  - pillow=8.3.1
  - scipy=1.7.1
  - numpy=1.19.5
  - python=3.7
  - h5py=3.1.0
  - matplotlib=3.4.2
  - pip
  - pip:
    - tensorflow==2.5
    - tensorboard==2.5
    - protobuf==3.9.2
    - keras-nlp==0.3.0
    - tensorflow-text==2.10
